server:
  port: 3335
spring:
  application:
    name: CartMS
  cloud:
    consul:
      host: localhost
      discovery:
        hostname: localhost
      config:
        fail-fast: false
        enabled: true
        prefix: config
        defaultContext: application
        data-key: data
        profileSeparator: '::'
        format: YAML


eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

management:
  health:
    circuitbreakers:
      enabled : true
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: always

resilience4j:
  circuitbreaker:
    instances:
      ProductMS:
        registerHealthIndicator: true
        eventConsumerBufferSize: 10
        failureRateThreshold: 60
        minimumNumberOfCalls: 6
        automaticTransitionFromOpenToHalfOpenEnabled: true
        waitDurationInOpenState: 3s
        permittedNumberOfCallsInHalfOpenState: 2
        slidingWindowSize: 10
        slidingWindowType: COUNT_BASED