drop schema  if exists  ekart_customercart;
create schema ekart_customercart;
use `ekart_customercart`;
CREATE TABLE EK_CUSTOMER_CART (
	CART_ID INT auto_increment,
    CUSTOMER_EMAIL_ID VARCHAR(50) unique,
	constraint EK_CART_ID_PK primary key (CART_ID)
);
INSERT INTO EK_CUSTOMER_CART (CART_ID,  CUSTOMER_EMAIL_ID) VALUES (3000,  'tom@infosys.com');
INSERT INTO EK_CUSTOMER_CART (CART_ID, CUSTOMER_EMAIL_ID) VALUES (3001,  'harry@infosys.com');
INSERT INTO EK_CUSTOMER_CART (CART_ID, CUSTOMER_EMAIL_ID) VALUES (3002,  'john@infosys.com');
INSERT INTO EK_CUSTOMER_CART (CART_ID, CUSTOMER_EMAIL_ID) VALUES (3003,  'sara@infosys.com');
INSERT INTO EK_CUSTOMER_CART (CART_ID, CUSTOMER_EMAIL_ID) VALUES (3004,  'mariya@infosys.com');
INSERT INTO EK_CUSTOMER_CART (CART_ID, CUSTOMER_EMAIL_ID) VALUES (3005,  'james@infosys.com');


commit;

SELECT * FROM EK_CUSTOMER_CART;

CREATE TABLE EK_CART_PRODUCT
(
CART_PRODUCT_ID INT auto_increment, 
CART_ID INT,
PRODUCT_ID INT NOT NULL,
QUANTITY SMALLINT,
constraint EK_CART_PRODUCT_ID_PK primary key (CART_PRODUCT_ID ),
constraint EK_CART_PRODUCT_ID_CUSTOMER_CART_FK foreign key (CART_ID) references EK_CUSTOMER_CART (CART_ID)
);


INSERT INTO EK_CART_PRODUCT (CART_PRODUCT_ID,CART_ID, PRODUCT_ID, QUANTITY) VALUES (8000 ,3000 , 1006,1 );
INSERT INTO EK_CART_PRODUCT (CART_PRODUCT_ID,CART_ID, PRODUCT_ID, QUANTITY) VALUES  (8001,3000 , 1008,1);
INSERT INTO EK_CART_PRODUCT (CART_PRODUCT_ID,CART_ID, PRODUCT_ID, QUANTITY) VALUES (8002,3001, 1073,2);
INSERT INTO EK_CART_PRODUCT (CART_PRODUCT_ID,CART_ID, PRODUCT_ID, QUANTITY) VALUES (8003,3002,1045 ,1);
INSERT INTO EK_CART_PRODUCT (CART_PRODUCT_ID,CART_ID, PRODUCT_ID, QUANTITY)  VALUES (8004,3002,1054 ,1);
INSERT INTO EK_CART_PRODUCT (CART_PRODUCT_ID,CART_ID, PRODUCT_ID, QUANTITY) VALUES (8005,3003,1034 ,3);
INSERT INTO EK_CART_PRODUCT (CART_PRODUCT_ID,CART_ID, PRODUCT_ID, QUANTITY)  VALUES (8006,3003,1035 ,4);
INSERT INTO EK_CART_PRODUCT (CART_PRODUCT_ID,CART_ID, PRODUCT_ID, QUANTITY) VALUES (8007,3004, 1074,10);
INSERT INTO EK_CART_PRODUCT (CART_PRODUCT_ID,CART_ID, PRODUCT_ID, QUANTITY)  VALUES (8008,3005, 1033 ,1);
INSERT INTO EK_CART_PRODUCT (CART_PRODUCT_ID,CART_ID, PRODUCT_ID, QUANTITY)  VALUES (8009,3005,1034 ,1);
INSERT INTO EK_CART_PRODUCT (CART_PRODUCT_ID,CART_ID, PRODUCT_ID, QUANTITY)  VALUES (8010,3005,1035 ,1);
INSERT INTO EK_CART_PRODUCT (CART_PRODUCT_ID,CART_ID, PRODUCT_ID, QUANTITY)  VALUES (8011,3005,1036 ,1);

SELECT * FROM EK_CART_PRODUCT;