#Configure the below given properties in PaymentMS.yml of consul server
spring.application.name=Payment-service
server.port=3337

#spring.datasource.url=jdbc:mysql://localhost:3306/EKART_PAYMENT?useSSL=false
spring.datasource.url=jdbc:mysql://localhost:3306/EKART_PAYMENT

#Configure the below common properties in application.yml of consul server
spring.datasource.username=root
spring.datasource.password=root

spring.jpa.show-sql=true

#logging.level.org.hibernate.type=info
spring.jpa.properties.hibernate.show_sql: true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.hibernate.ddl-auto=update
#spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect


#server.error.whitelabel.enabled=false
server.servlet.context-path=/Ekart
#spring.cloud.consul.discovery.health-check-url =  http://localhost:${server.port}${server.servlet.context-path}/actuator

eureka.client.service-url.defaultZone= http://localhost:8761/eureka/
eureka.client.fetch-registry= true
eureka.client.register-with-eureka= true
