#Configure the below given properties in ProductMS.yml of consul server

spring.application.name=Product-service
server.port=3334
spring.datasource.url=jdbc:mysql://localhost:3306/EKART_PRODUCT?allowPublicKeyRetrieval=true&useSSL=false
#spring.datasource.url=jdbc:mysql://localhost:3306/EKART_PRODUCT

#Configure the below common properties in application.yml of consul server
spring.datasource.username=root
spring.datasource.password=root
server.servlet.context-path=/Ekart
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
logging.level.org.hibernate.type=info

spring.jpa.properties.hibernate.show_sql: true
#spring.cloud.consul.discovery.health-check-url =  http://localhost:${server.port}${server.servlet.context-path}/actuator


eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true